import { useState, useEffect } from "react";
import { ShieldAlert, RefreshCw, Send, Check } from "lucide-react";
import { Thought } from "../../types";

interface DevilsAdvocateProps {
  topic: string;
  onAddThought: (text: string) => void;
  thoughts: Thought[];
}

export default function DevilsAdvocate({ topic, onAddThought, thoughts }: DevilsAdvocateProps) {
  const [challenges, setChallenges] = useState<string[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [response, setResponse] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchChallenges();
  }, [topic]);

  const fetchChallenges = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/session/devils-advocate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          topic,
          recentThoughts: thoughts.slice(0, 8),
        }),
      });
      if (res.ok) {
        const data = await res.json();
        if (data.challenges && data.challenges.length > 0) {
          setChallenges(data.challenges);
        } else {
          throw new Error("Invalid response format");
        }
      } else {
        throw new Error("HTTP error " + res.status);
      }
    } catch (e) {
      console.error(e);
      setChallenges([
        "Are you using this process to avoid a different, much harder decision?",
        "If you do absolutely nothing about this for six months, what would actually break?",
        "Is there a chance your standard of 'success' here is actually unrealistic?"
      ]);
    } finally {
      setLoading(false);
    }
  };

  const handleSave = () => {
    if (!response.trim()) return;
    const challenge = challenges[currentIndex];
    onAddThought(`Pressure-Test Challenge: [${challenge}] -> Response: [${response.trim()}]`);
    setResponse("");

    if (currentIndex < challenges.length - 1) {
      setCurrentIndex((prev) => prev + 1);
    } else {
      setCurrentIndex((prev) => prev + 1);
    }
  };

  return (
    <div className="space-y-6" id="devils-advocate-mode">
      <div className="bg-white border-3 border-black p-4.5 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] flex items-start gap-4">
        <ShieldAlert className="w-5 h-5 text-black shrink-0 mt-0.5" />
        <div className="flex-1">
          <h3 className="font-display font-black text-xs uppercase text-black tracking-wider">Devil's Advocate Pressure Test</h3>
          <p className="text-[11px] text-zinc-650 leading-normal mt-0.5 font-sans">
            Pressure-test opinions or comfort zones. Respond directly to uncomfortable counterarguments generated by Gemini to lock down what you truly believe.
          </p>
        </div>
        <button
          onClick={fetchChallenges}
          className="p-1 px-2.5 border-2 border-black bg-white hover:bg-zinc-100 text-black text-[10px] font-bold font-mono uppercase tracking-wider cursor-pointer"
          disabled={loading}
        >
          Re-Analyze
        </button>
      </div>

      {loading ? (
        <div className="py-12 text-center text-zinc-500 flex flex-col items-center justify-center gap-2">
          <RefreshCw className="w-5 h-5 animate-spin text-black" />
          <span className="text-xs font-mono uppercase tracking-wider">Generating critical pressure-challenges...</span>
        </div>
      ) : currentIndex < challenges.length ? (
        <div className="space-y-4">
          <div className="p-5 bg-white border-2 border-black">
            <span className="text-[10px] uppercase font-mono font-bold tracking-wider text-black block mb-1.5">Challenge {currentIndex+1} of {challenges.length}</span>
            <p className="text-sm font-bold text-black leading-relaxed font-sans italic">
              "{challenges[currentIndex]}"
            </p>
          </div>

          <div className="space-y-2">
            <span className="block text-[11px] font-mono font-bold text-zinc-700 uppercase tracking-wider">Your direct, honest defense:</span>
            <input
              type="text"
              placeholder="e.g., Actually, six months of silence would lose us prime momentum..."
              value={response}
              onChange={(e) => setResponse(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && response.trim() && handleSave()}
              className="w-full text-xs font-mono border-2 border-black bg-white p-3.5 focus:outline-none"
            />
          </div>

          <div className="flex justify-end gap-2 text-xs">
            <button
              onClick={() => setCurrentIndex((prev) => prev + 1)}
              className="px-4 py-2 hover:underline text-black font-display font-bold uppercase tracking-wider cursor-pointer"
            >
              Skip Challenge
            </button>
            <button
              disabled={!response.trim()}
              onClick={handleSave}
              className="px-5 py-2.5 border-2 border-black bg-black text-white hover:bg-[#F8F7F4] hover:text-black font-display font-black text-xs uppercase tracking-wider flex items-center gap-1.5 transition cursor-pointer shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]"
            >
              <Send className="w-3.5 h-3.5" />
              Capture Reaction
            </button>
          </div>
        </div>
      ) : (
        <div className="text-center py-12 p-8 space-y-4 border-2 border-dashed border-zinc-300">
          <div className="p-3 bg-black text-white border border-black inline-block">
            <Check className="w-8 h-8" />
          </div>
          <h2 className="text-sm font-display font-black uppercase text-black">Pressure Test Completed!</h2>
          <p className="text-xs text-zinc-500 font-sans max-w-xs mx-auto">Your defensive core lines have been stockpiled. Synthesize results now!</p>
        </div>
      )}
    </div>
  );
}
